
# Guidelines for Reviewers {-#CGuideReviewers}


The reviewer report allows you to offer constructive assistance and criticism to the author(s). Please be sensitive to the author(s) and convey your feedback in a positive way. Your comments should include a brief summary of what you think the author is trying to accomplish, a discussion of any flaws you feel the chapter(s) may contain, and detailed directions for recommended changes. The best reviewer reports are done in collaboration between senior (more experienced) and junior (closer to the textbooks’ intended readership) reviewers. Students in your classes also make great (supplement) reviewers - this is our intended audience.

A.  **Audience of the Reviewers Report.** The starting point of any writing project is deciding on the audience. For your report, there are really three audience members: (a) the editorial team; (b) the author(s); and (c) yourself, as a representative of the actuarial community.

B.  **Read the Chapter**. Start by reading the chapter quickly so as to get the key ideas. As you go, jot down a few notes about what the author(s) are doing. Then, think for a while about the big picture -- what are the authors trying to do, whether they are taking the best approach, and how successful are they at their approach. Then, jot down some further notes about the paper and highlight any major concerns that you had on this first reading.

Then, read the chapter carefully, as if it were one written by a colleague or student.  As you go through the chapter, you should make notes on the following, perhaps in the margins of the chapter itself, about:

*   The key substantive ideas that the author is seeking to convey to the reader: (a) the topics that are being studied, (b) the tools used; (c) the logical arguments made; (d) the conclusions reached; and (e) whether the chapter learning objectives are demonstrated.

*   Central problem areas in the chapter. These include places where (a) the description of the topics is inappropriate to the actual material in the paper; (b) the modeling tools are being used inappropriately; (c) there is only a loose link between the model and the empirics; (d) the conclusions are incorrectly made or expressed; and (e) the contribution to the literature is inaccurately described.

*   Smaller difficulties with the chapter. These include (a) areas where the author's line of thought is hard to follow; (b) spots with spelling and grammatical problems; (c) missing data sources and poorly constructed tables or figures; (d) references to the literature that are missing or incorrect.

 C.  **Provide Feedback to the Author.** It is important that the author(s) benefit from the hard work that you have put into reviewing the chapter. Depending on the nature and status of the chapter, this feedback might include:

*   Comments on areas where the logical argument in the chapter was hard to follow, important mathematical derivations were obscure, or empirical work was incompletely described.
*   Comments on areas where the exposition was weak.
*   Reports on small problems organized by page.

D. **Detailed Feedback**. Most author/editorial teams could really benefit from detailed feedback on items that sometime miss "big picture" reviews but are critical for student understanding. It would be very helpful if you could provide detailed feedback on:

*  *Learning Outcomes*
*  *End of the Section Quizzes*
*  *Online Glossary*
*  *Exercises*
*  *Data Availability and Clarity of Illustrative `R` Code*

E. **Ways to Review**

Everything is open source and available on the web. In principle, one could make suggestions directly on GitHub. However, in earlier rounds of reviewing we found this approach was not helpful for this generation of authors and reviewers. Alternative, you can make notes by referring to Section/paragraphs/lines or Tables or Figures. Alternatively, some prefer to print to pdf the .html version and make comments on the pdf version. (As we get closer to finalizing the edition, we will also make a pdf version.) You choose the method that works best for you.

